[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "mkdir -p media/murojaatlar media/tekshiruvlar && python manage.py migrate --noinput && python manage.py seed_data && python -m gunicorn core.wsgi --bind 0.0.0.0:$PORT --workers 2"
