# Generated by Django 6.0.3 on 2026-03-14 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feed_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maktab',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='murojaatrasm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statistika',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tekshiruv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MaktabIzoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_full_name', models.CharField(blank=True, max_length=200)),
                ('matn', models.TextField(max_length=500)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='app.maktab')),
            ],
            options={
                'verbose_name': 'Maktab izohi',
                'verbose_name_plural': 'Maktab izohlari',
                'ordering': ['-vaqt'],
            },
        ),
    ]
