# Generated by Django 6.0.3 on 2026-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_maktab_id_alter_murojaat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojaat',
            name='infratuzilma',
            field=models.CharField(blank=True, choices=[('maktab', 'Maktab'), ('bogcha', "Bog'cha"), ('shifoxona', 'Shifoxona'), ('yol', "Yo'l infratuzilmasi"), ('sport', 'Sport inshootlari'), ('boshqa', 'Boshqa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='sektor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='tuman',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='viloyat',
            field=models.CharField(blank=True, choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent_v', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('buxoro', 'Buxoro viloyati'), ('xorazm', 'Xorazm viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=100),
        ),
    ]
