# Generated by Django 6.0.3 on 2026-03-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_murojaat_infratuzilma_alter_murojaat_sektor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktab',
            name='tur',
            field=models.CharField(choices=[('maktab', 'Maktab'), ('bogcha', "Bog'cha"), ('shifoxona', 'Shifoxona'), ('sport', 'Sport inshoot')], default='maktab', max_length=30),
        ),
    ]
